package hz.blog.markhub.mapper;

import hz.blog.markhub.domain.UserDo;

public interface UserDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Sun Aug 14 01:04:22 EDT 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Sun Aug 14 01:04:22 EDT 2022
     */
    int insert(UserDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Sun Aug 14 01:04:22 EDT 2022
     */
    int insertSelective(UserDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Sun Aug 14 01:04:22 EDT 2022
     */
    UserDo selectByPrimaryKey(Long id);

    UserDo selectByUserName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Sun Aug 14 01:04:22 EDT 2022
     */
    int updateByPrimaryKeySelective(UserDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_user
     *
     * @mbg.generated Sun Aug 14 01:04:22 EDT 2022
     */
    int updateByPrimaryKey(UserDo row);
}